general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 3
}

listener {
    timeout = 2700
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 3600
    on-timeout = pidof hyprlock || hyprlock
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
