# Kitana managed Hypridle config

general {
    lock_cmd = ${KITANA_DIR:-$HOME/.local/share/kitana}/bin/kitana-lock
    before_sleep_cmd = ${KITANA_DIR:-$HOME/.local/share/kitana}/bin/kitana-lock
    after_sleep_cmd = sh -c "sleep 3; hyprctl dispatch 'hl.dsp.dpms({ action = \"enable\" })'"
    inhibit_sleep = 3
}

listener {
    timeout = 2700
    on-timeout = ${KITANA_DIR:-$HOME/.local/share/kitana}/bin/kitana-lock
}

listener {
    timeout = 3600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = sh -c "sleep 3; hyprctl dispatch 'hl.dsp.dpms({ action = \"enable\" })'"
}

listener {
    timeout = 7200
    on-timeout = systemctl suspend
}
