# Kitana managed Hyprpaper config

splash = false
ipc = true

wallpaper {
    monitor = 
    path = ~/.local/share/kitana/default/hypr/walls/mystical_night_town_default.jpg
    fit_mode = cover
}

# Uncomment and configure your wallpapers for specific monitors if needed
# wallpaper {
#     monitor = eDP-1
#     path = ~/.local/share/kitana/default/hypr/walls/wall01.jpg
# }

# wallpaper {
#     monitor = DP-2
#     path = ~/.local/share/kitana/default/hypr/walls/wall02.jpg
# }
