splash = false
ipc = false

wallpaper {
    monitor = 
    path = ~/.config/hypr/walls/mystical_night_town_default.jpg
}

# Uncomment and configure your wallpapers for specific monitors if needed
# wallpaper {
#     monitor = eDP-1
#     path = ~/.config/hypr/wall01.jpg
# }

# wallpaper {
#     monitor = DP-2
#     path = ~/.config/hypr/wall02.jpg
# }
