return {
  slug = "catppuccin-mocha",
  name = "Catppuccin Mocha",

  colors = {
    rosewater = "#f5e0dc",
    flamingo = "#f2cdcd",
    pink = "#f5c2e7",
    mauve = "#cba6f7",
    red = "#f38ba8",
    maroon = "#eba0ac",
    peach = "#fab387",
    yellow = "#f9e2af",
    green = "#a6e3a1",
    teal = "#94e2d5",
    sky = "#89dceb",
    sapphire = "#74c7ec",
    blue = "#89b4fa",
    lavender = "#b4befe",
    text = "#cdd6f4",
    subtext1 = "#bac2de",
    subtext0 = "#a6adc8",
    overlay2 = "#9399b2",
    overlay1 = "#7f849c",
    overlay0 = "#6c7086",
    surface2 = "#585b70",
    surface1 = "#45475a",
    surface0 = "#313244",
    base = "#1e1e2e",
    mantle = "#181825",
    crust = "#11111b",
  },

  kitana = {
    crust0 = "crust",
    crust1 = "mantle",
    mantle0 = "mantle",
    mantle1 = "surface0",
    base0 = "base",
    base1 = "surface0",
    surface0 = "surface0",
    surface1 = "surface1",
    overlay0 = "surface1",
    overlay1 = "overlay2",
    subtext0 = "overlay2",
    subtext1 = "subtext1",
    text0 = "text",
    text1 = "rosewater",
    accent0 = "mauve",
    accent1 = "lavender",
    warning0 = "yellow",
    danger0 = "red",

    hypr = {
      border_active = "accent0",
      border_inactive = "surface1",
    },
  },

  ghostty = {
    theme = "Catppuccin Mocha",
  },

  zed = {
    source_url = "https://raw.githubusercontent.com/catppuccin/zed/main/themes/catppuccin-mauve.json",
    source_file = "vendor/zed/catppuccin-mocha.json",
    theme_name = "Catppuccin Mocha",
  },
}
