return {
	slug = "kanagawa-dragon",
	name = "Kanagawa Dragon",

	colors = {
		sumiInk0 = "#16161d",
		sumiInk1 = "#181616",
		sumiInk2 = "#1a1a22",
		sumiInk3 = "#1f1f28",
		sumiInk4 = "#2a2a37",
		waveBlue1 = "#223249",
		waveBlue2 = "#2d4f67",
		winterGreen = "#2b3328",
		winterYellow = "#49443c",
		winterRed = "#43242b",
		winterBlue = "#252535",
		autumnGreen = "#76946a",
		autumnRed = "#c34043",
		autumnYellow = "#dca561",
		samuraiRed = "#e82424",
		roninYellow = "#ff9e3b",
		waveAqua1 = "#6a9589",
		dragonBlue = "#8ba4b0",
		fujiWhite = "#c5c9c5",
		oldWhite = "#c8c093",
		springViolet1 = "#8992a7",
		oniViolet = "#a292a3",
		crystalBlue = "#7e9cd8",
		springViolet2 = "#9cabca",
		springBlue = "#7fb4ca",
		lightBlue = "#a3d4d5",
		waveAqua2 = "#7aa89f",
		springGreen = "#87a987",
		boatYellow1 = "#938056",
		boatYellow2 = "#c0a36e",
		carpYellow = "#e6c384",
		sakuraPink = "#d27e99",
		waveRed = "#e46876",
		peachRed = "#ff5d62",
		surimiOrange = "#ffa066",
		katanaGray = "#717c7c",
		dragonBlack0 = "#0d0c0c",
		dragonBlack1 = "#12120f",
		dragonBlack2 = "#1d1c19",
		dragonBlack3 = "#181616",
		dragonBlack4 = "#282727",
		dragonBlack5 = "#393836",
		dragonWhite = "#c5c9c5",
		dragonGreen = "#87a987",
		dragonGreen2 = "#8a9a7b",
		dragonPink = "#a292a3",
		dragonOrange = "#b6927b",
		dragonOrange2 = "#b98d7b",
		dragonGray = "#a6a69c",
		dragonGray2 = "#9e9b93",
		dragonGray3 = "#7a8382",
		dragonBlue2 = "#8ba4b0",
		dragonViolet = "#8992a7",
		dragonRed = "#c4746e",
		dragonAqua = "#8ea4a2",
		dragonAsh = "#737c73",
		dragonTeal = "#949fb5",
		dragonYellow = "#c4b28a",
	},

	kitana = {
		quickshell = {
			foreground = "dragonWhite",
			foregroundStrong = "dragonGray",
			foregroundMuted = "dragonGray",
			foregroundSubtle = "dragonGray",
			foregroundInverted = "dragonBlack3",

			accent = "dragonGreen",
			accentStrong = "dragonViolet",
			onAccent = "dragonBlack3",

			background = "sumiInk1",
			surface = "dragonBlack3",
			surfaceContainer = "dragonBlack3",
			surfaceCard = "sumiInk3",
			surfaceControl = "sumiInk3",
			surfaceSubtle = "dragonBlack5",
			surfaceHover = "dragonBlack5",
			surfacePressed = "dragonBlack5",
			surfaceActive = "dragonGreen",
			surfaceSelected = "dragonGreen",
			surfaceFloating = "sumiInk1",
			surfaceFloatingStrong = "sumiInk3",

			border = "sumiInk3",
			borderSubtle = "sumiInk3",
			borderMuted = "sumiInk4",
			borderStrong = "dragonBlack5",
			borderFocus = "dragonGreen",

			info = "crystalBlue",
			success = "dragonGreen",
			warning = "dragonYellow",
			danger = "dragonRed",

			iconPrimary = "dragonWhite",
			iconSecondary = "dragonGray",
			iconMuted = "dragonGray",
			iconSubtle = "dragonGray",
			iconAccent = "dragonGreen",
			iconOnAccent = "dragonBlack3",
			iconInverse = "dragonBlack3",
			iconBrand = "dragonGreen",
			iconDisabled = "dragonGray",
			iconDanger = "dragonRed",
		},

		hypr = {
			border_active = "accent",
			border_inactive = "borderStrong",
		},
	},

	ghostty = {
		theme = "Kanagawa Dragon",
	},

	zed = {
		source_url = "https://raw.githubusercontent.com/ethangilmore/zed-kanagawa/main/themes/Kanagawa.json",
		source_file = "vendor/zed/kanagawa-dragon.json",
		theme_name = "Kanagawa Dragon",
	},

	neovim = {
		colorscheme = "kanagawa",
	},
}
