return {
  slug = "tokyo-night",
  name = "Tokyo Night",

  colors = {
    bg = "#1a1b26",
    bg_dark = "#16161e",
    bg_surface = "#24283b",
    bg_highlight = "#292e42",
    terminal_black = "#414868",
    fg = "#c0caf5",
    fg_dark = "#a9b1d6",
    fg_gutter = "#3b4261",
    dark3 = "#545c7e",
    comment = "#565f89",
    dark5 = "#737aa2",
    blue0 = "#3d59a1",
    blue = "#7aa2f7",
    cyan = "#7dcfff",
    blue1 = "#2ac3de",
    blue2 = "#0db9d7",
    blue5 = "#89ddff",
    blue6 = "#b4f9f8",
    blue7 = "#394b70",
    magenta = "#bb9af7",
    magenta2 = "#ff007c",
    purple = "#9d7cd8",
    orange = "#ff9e64",
    yellow = "#e0af68",
    green = "#9ece6a",
    green1 = "#73daca",
    green2 = "#41a6b5",
    teal = "#1abc9c",
    red = "#f7768e",
    red1 = "#db4b4b",
  },

  kitana = {
    crust0 = "bg_dark",
    crust1 = "bg_surface",
    mantle0 = "bg_dark",
    mantle1 = "bg_highlight",
    base0 = "bg",
    base1 = "bg_surface",
    surface0 = "bg_surface",
    surface1 = "terminal_black",
    overlay0 = "terminal_black",
    overlay1 = "comment",
    subtext0 = "comment",
    subtext1 = "fg_dark",
    text0 = "fg",
    text1 = "#ffffff",
    accent0 = "blue",
    accent1 = "cyan",
    warning0 = "yellow",
    danger0 = "red",

    hypr = {
      border_active = "accent0",
      border_inactive = "terminal_black",
    },
  },

  ghostty = {
    theme = "TokyoNight",
  },

  zed = {
    source_url = "https://raw.githubusercontent.com/ssaunderss/zed-tokyo-night/main/themes/tokyo-night.json",
    source_file = "vendor/zed/tokyo-night.json",
    theme_name = "Tokyo Night",
  },
}
