return {
  slug = "tokyo-night",
  name = "Tokyo Night",

  colors = {
    bg = "#1a1b26",
    bg_dark = "#16161e",
    bg_surface = "#24283b",
    bg_highlight = "#292e42",
    terminal_black = "#414868",
    fg = "#c0caf5",
    fg_dark = "#a9b1d6",
    fg_gutter = "#3b4261",
    dark3 = "#545c7e",
    comment = "#565f89",
    dark5 = "#737aa2",
    blue0 = "#3d59a1",
    blue = "#7aa2f7",
    cyan = "#7dcfff",
    blue1 = "#2ac3de",
    blue2 = "#0db9d7",
    blue5 = "#89ddff",
    blue6 = "#b4f9f8",
    blue7 = "#394b70",
    magenta = "#bb9af7",
    magenta2 = "#ff007c",
    purple = "#9d7cd8",
    orange = "#ff9e64",
    yellow = "#e0af68",
    green = "#9ece6a",
    green1 = "#73daca",
    green2 = "#41a6b5",
    teal = "#1abc9c",
    red = "#f7768e",
    red1 = "#db4b4b",
  },

  kitana = {
    quickshell = {
      foreground = "fg",
      foregroundStrong = "#ffffff",
      foregroundMuted = "dark5",
      foregroundSubtle = "dark5",
      foregroundDisabled = "dark5",
      foregroundInverted = "bg_dark",

      accent = "blue",
      accentStrong = "cyan",
      onAccent = "bg_dark",
      accentBackground = "blue",
      accentSelectedBackground = "blue",

      background = "bg",
      surface = "bg_dark",
      surfaceContainer = "bg_dark",
      surfaceCard = "bg_surface",
      surfaceControl = "bg_surface",
      surfaceSubtle = "terminal_black",
      surfaceHover = "terminal_black",
      surfacePressed = "terminal_black",
      surfaceActive = "blue",
      surfaceSelected = "blue",
      surfaceFloating = "bg",
      surfaceFloatingStrong = "bg_surface",

      border = "bg_surface",
      borderMuted = "terminal_black",
      borderStrong = "terminal_black",
      borderFocus = "blue",

      info = "blue",
      success = "green",
      warning = "yellow",
      danger = "red",
      infoBackground = "blue",
      successBackground = "green",
      warningBackground = "yellow",
      dangerBackground = "red",

      iconPrimary = "fg",
      iconSecondary = "#ffffff",
      iconMuted = "dark5",
      iconSubtle = "dark5",
      iconAccent = "blue",
      iconOnAccent = "bg_dark",
      iconInverse = "bg_dark",
      iconBrand = "blue",
      iconDisabled = "dark5",
      iconDanger = "red",

      scrim = "bg_surface",
      scrimSoft = "bg_surface",
      imageOverlay = "bg_surface",
      shadow = "#000000",
    },

    hypr = {
      border_active = "accent",
      border_inactive = "terminal_black",
    },
  },

  ghostty = {
    theme = "TokyoNight",
  },

  zed = {
    source_url = "https://raw.githubusercontent.com/ssaunderss/zed-tokyo-night/main/themes/tokyo-night.json",
    source_file = "vendor/zed/tokyo-night.json",
    theme_name = "Tokyo Night",
  },

  neovim = {
    colorscheme = "tokyonight",
  },
}
